### ISSUE TITLE
Scan does not use local image

### ISSUE THREAD

**Issue by TechDufus** [neuvector/scan-action#17]
When working in a github action, using `docker-build-push-action@v5` to build a local image and then immediately using `neuvector/scan-action@main` to scan that image, the scan is attempting to reach out to hub.docker.com for the image instead of the freshly built local one and it fails with the following error:
```
2024-11-01T16:51:25.422|ERRO|SCN|main.scanOnDemand: Failed to scan repository - error=Image not found registry=https://registry.hub.docker.com/ repo=ghcr.io/our-org/our-image tag=dev
Image: https://registry.hub.docker.com/ghcr.io/our-org/our-image:dev
neuvector.scanner
jq: error (at <stdin>:4): Cannot iterate over null (null)
```

Here is an example config we are using to build and scan the image:
```yaml
      - name: Docker Build
        uses: docker/build-push-action@v5
        with:
          context: ${{ env.CONTEXT_PATH }}
          file: ${{ env.DOCKERFILE_PATH }}
          platforms: linux/amd64,linux/arm64
          push: false
          tags: |
            ${{ env.GHCR_REGISTRY }}/${{ env.GHCR_REPOSITORY }}/${{ env.IMAGE_NAME }}:${{ env.TAG }}

      - name: Scan ${{ env.IMAGE_NAME }} Image
        continue-on-error: false
        uses: neuvector/scan-action@main
        with:
          debug: true
          image-repository: ${{ env.GHCR_REGISTRY }}/${{ env.GHCR_REPOSITORY }}/${{ env.IMAGE_NAME }}
          image-tag: ${{ env.TAG }}
          min-high-cves-to-fail: "${{ env.SCAN_MIN_HIGH_CVES_TO_FAIL }}"
          min-medium-cves-to-fail: "${{ env.SCAN_MIN_MED_CVES_TO_FAIL }}"
```

Can anyone tell me why the scan-action is looking at https://registry.hub.docker.com for the image instead of the built one?

We have a lot of other scans that all fail with this `jq` error, and after pulling the action code and running the `run-scan.sh`, the jq errors because it's hard-coded to look at the `.report.vulnerabilities` list, but if the image doesn't exist, the `scan_result.json` contains the following content:
```json
{
    "error_message": "Image not found",
    "report": null
}
```

Ideally some kind of pre-check on the `scan_result.json` to confirm either `error_message:` is empty, or that `report` is non-null before continuing with the `jq` queries would be a good addition for folks looking at the logs to see why this action failed.

**Comment by TechDufus** [comment]
I added a step in between these to basically `docker image ls`, and it turns out that the image produced by this `docker/build-push-action` gives random guid names/tags to images, which the `scan-action` obviously doesn't recognize.

After switching to this flow, it appears to be working for us:
```yaml
      - name: Docker Build
        run: |
          docker build \
            -t ${{ env.GHCR_REGISTRY }}/${{ env.GHCR_REPOSITORY }}/${{ env.IMAGE_NAME }}:${{ env.TAG }} \
            ${{ env.CONTEXT_PATH }} \

      - name: Scan ${{ env.IMAGE_NAME }} Image
        continue-on-error: false
        uses: neuvector/scan-action@main
        with:
          debug: true
          image-repository: ${{ env.GHCR_REGISTRY }}/${{ env.GHCR_REPOSITORY }}/${{ env.IMAGE_NAME }}
          image-tag: ${{ env.TAG }}
          min-high-cves-to-fail: "${{ env.SCAN_MIN_HIGH_CVES_TO_FAIL }}"
          min-medium-cves-to-fail: "${{ env.SCAN_MIN_MED_CVES_TO_FAIL }}"
```

I suppose this is just user error, but I wanted it documented in case others run into this `Image not found` and maybe this helps.
