### ISSUE TITLE
Output values are empty.

### ISSUE THREAD

**Issue by TechDufus** [neuvector/scan-action#19]
I have the below 2 steps, and you can see in my 2nd step, I'm attempting to reference the scan output counts and pump that into the step summary, but there is no text/values behind my references.

Is there something wrong with the output from this action? Or are my references just wrong?

## Steps:
```yaml
      - name: Scan ${{ inputs.IMAGE_NAME }} Image
        continue-on-error: ${{ fromJSON(inputs.CONTINUE_ON_ERROR) }}
        uses: neuvector/scan-action@main
        id: neuvector-scan
        with:
          debug: ${{ fromJSON(inputs.SCAN_DEBUG) }}
          image-repository: ${{ inputs.GHCR_REGISTRY }}/${{ inputs.GHCR_REPOSITORY }}/${{ inputs.IMAGE_NAME }}
          image-tag: ${{ inputs.VERSION }}
          min-high-cves-to-fail: "${{ inputs.SCAN_MIN_HIGH_CVES_TO_FAIL }}"
          min-medium-cves-to-fail: "${{ inputs.SCAN_MIN_MED_CVES_TO_FAIL }}"

      - name: NeuVector Security Scan Results
        shell: bash
        run: |
          echo "<h2>🔒NeuVector Scan Results</h1>" >> $GITHUB_STEP_SUMMARY
          echo "<table>" >> $GITHUB_STEP_SUMMARY
          echo "  <tr><th>🚨High CVEs Found</th><td>${{ steps.neuvector-scan.outputs.high_vulnerability_count }}</td></tr>" >> $GITHUB_STEP_SUMMARY
          echo "  <tr><th>⚠️Medium CVEs Found</th><td>${{ steps.neuvector-scan.outputs.medium_vulnerability_count }}</td></tr>" >> $GITHUB_STEP_SUMMARY
          echo "  <tr><th>⛔Total CVEs Found</th><td>${{ steps.neuvector-scan.outputs.vulnerability_count }}</td></tr>" >> $GITHUB_STEP_SUMMARY
          echo "</table>" >> $GITHUB_STEP_SUMMARY
          echo "<p>For more details, please see this workflow's logs.</p>" >> $GITHUB_STEP_SUMMARY

```

## Resulting HTML Table:
```html
<h2>🔒NeuVector Scan Results</h1>
<table>
  <tr><th>🚨High CVEs Found</th><td></td></tr>
  <tr><th>⚠️Medium CVEs Found</th><td></td></tr>
  <tr><th>⛔Total CVEs Found</th><td></td></tr>
</table>
<p>For more details, please see this workflow's logs.</p>
```

## Rendered HTML Table:

<h2>🔒NeuVector Scan Results</h1>
<table>
  <tr><th>🚨High CVEs Found</th><td></td></tr>
  <tr><th>⚠️Medium CVEs Found</th><td></td></tr>
  <tr><th>⛔Total CVEs Found</th><td></td></tr>
</table>
<p>For more details, please see this workflow's logs.</p>
